name: Générer Excel des traductions

on:
  push:
    paths:
      - 'fr/*.json'
    branches:
      - main

jobs:
  generate_excel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Installer Python et dépendances
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les librairies Python
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Générer les fichiers Excel
        run: python generate_excel_diff.py

      - name: Commit des fichiers Excel mis à jour
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add excels/*.xlsx
          git commit -m "MAJ auto des fichiers Excel après traduction" || echo "Aucune modification"
          git push
